server:
  port: 8444
spring:
  application:
    name: "ms-technology"
  devtools:
    add-properties: false
  main:
    web-application-type: "reactive"
  r2dbc:
    url: "r2dbc:postgresql://localhost:5432/reactive_backend?currentSchema=ms_capacity"
    username: "postgres"
    password: "root"
  sql:
    init:
      mode: "always"
logging:
  level:
    org.springframework.r2dbc: "DEBUG"