CREATE TABLE IF NOT EXISTS MS_CAPACITY.CAPACITIES (
	ID INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	NAME VARCHAR(50) NOT NULL UNIQUE,
	DESCRIPTION VARCHAR(90) NOT NULL,
	TECHNOLOGY_COUNT INT NOT NULL
)