server:
  port: 8443
spring:
  application:
    name: "ms-technology"
  devtools:
    add-properties: false
  r2dbc:
    url: "r2dbc:postgresql://localhost:5432/ms-technology"
    username: "postgres"
    password: "root"
  sql:
    init:
      mode: "always"
  main:
    web-application-type: "reactive"
  h2:
    console:
      enabled: true
      path: "/h2"
logging:
  level:
    org.springframework.r2dbc: "DEBUG"
management:
  health:
    diskspace:
      enabled: false
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
  endpoints:
    web:
      exposure:
        include: health
      base-path: /api/auto