##Spring Configuration
server:
  port: 8443
spring:
  application:
    name: ms-technology
  devtools:
    add-properties: false
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/ms-technology
    username: postgres
    password: root
  sql:
    init:
      mode: always
  main:
    web-application-type: reactive
  h2:
    console:
      enabled: true
      path: /h2
  profiles:
    include:
logging:
  level:
    org.springframework.r2dbc: DEBUG