CREATE TABLE MS_TECHNOLOGY.TECHNOLOGIES (
	ID INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	NAME VARCHAR(50) NOT NULL UNIQUE,
	DESCRIPTION VARCHAR(90) NOT NULL
)

CREATE TABLE IF NOT EXISTS MS_TECHNOLOGY.capacity_technology (
	ID INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	CAPACITY_ID INT NOT NULL,
	TECHNOLOGY_ID INT NOT NULL,
	FOREIGN KEY (TECHNOLOGY_ID) REFERENCES MS_TECHNOLOGY.TECHNOLOGIES(ID)
)